### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by Archikrim** [Archikrim/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by ArchikrimSecond** [comment]
- Every day life throws me a new challenge. Another challenge is to conquer the field of information technology. I'm not 20 years old, but I'm still young enough to start a developer career in a successful company and become a real professional in this industry as soon as possible. Did I choose this direction because of the money? Partly yes, but the main reason is endless self-development, which is the most important factor for me.

**Comment by Archikrim** [comment]
Great!
