### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by Archikrim** [Archikrim/homepage#6]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by ArchikrimSecond** [comment]
2021 
Pursue my goal.

2019 
I am a student again in IT Step Academy. I have a new goal in my life and want to start a new career in IT industry. 

2017
I am happy person because I found love of my life. Now she is my wife and supports me in everything. 

2005-2019 
In searching and finding myself. Via this time, I changed places for living and my jobs. I used to work a bartender, a sales manager in a big supermarket and even a sound engineer (with Ukrainian humoristic show). Finding myself took me a long time. :) 

2005 
Graduated from University. 

1999 
Became a student of Admiral Makarov National University of Shipbuilding in Mykolaiv, my specialty - mechanical engineer.

1989
Moved to Crimea, our historical motherland, with my family. Here I graduated from a high school.
 
1988 
My first school day, time of knowledge. When I went to school the first time, my grandma gave me 1 ruble to use it for my needs. For all this money I bought 10 enormous flatbreads and brought them at home. It was too much bread for my family. :)

My childhood: nice time of surprises and presents, world of fairy tale and magic :)
 
26-th February 1982 
Born in Marhamat, Uzbekistan
